plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
    id 'kotlin-parcelize'
    id 'androidx.navigation.safeargs.kotlin'
}

android {
    namespace 'com.bridge.androidtechnicaltest'
    compileSdk 34

    defaultConfig {
        applicationId "com.bridge.androidtechnicaltest"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlin {
        jvmToolchain(17)
    }
}

def koinVersion = "2.0.0"
def androidXLegacySupport = "1.0.0"
def roomVersion = "2.6.1"
def retrofitVersion = "2.9.0"
def okHttpVersion = "4.3.1"
def gsonVersion = "2.8.5"
def navComponentVersion = "2.5.3"
def ktVersion = "1.7.1"
def paging3Version = "3.2.1"
def retrofitVersion2 = "2.4.0"

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    // implementation "androidx.legacy:legacy-support-v4:$androidXLegacySupport"
    implementation "androidx.appcompat:appcompat:1.6.0"
    implementation "androidx.activity:activity-ktx:1.7.2"
    implementation "androidx.fragment:fragment-ktx:1.6.0"
    // implementation "androidx.recyclerview:recyclerview:1.1.0"
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.material:material:1.8.0'

    // Nav Component
    implementation "androidx.navigation:navigation-fragment-ktx:${navComponentVersion}"
    implementation "androidx.navigation:navigation-ui-ktx:${navComponentVersion}"

    // Coroutines
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:${ktVersion}"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:${ktVersion}"

    //Dagger - Hilt
    implementation("com.google.dagger:hilt-android:2.48")
    kapt("com.google.dagger:hilt-android-compiler:2.48")
    kapt("com.google.dagger:dagger-compiler:2.11")

    // LifeCycle
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.5.1"
    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:2.5.1"
    implementation "androidx.lifecycle:lifecycle-common-java8:2.5.1"
    implementation "androidx.lifecycle:lifecycle-process:2.5.1"

    //    Room
    implementation("androidx.room:room-ktx:${roomVersion}")
    implementation("androidx.room:room-runtime:$roomVersion")
    kapt("androidx.room:room-compiler:${roomVersion}")

    //Retrofit
    implementation("com.squareup.retrofit2:retrofit:${retrofitVersion}")
    implementation("com.google.code.gson:gson:${gsonVersion}")
    implementation("com.squareup.retrofit2:converter-gson:${retrofitVersion}")
    implementation("com.squareup.okhttp3:logging-interceptor:${okHttpVersion}")
    implementation("com.squareup.okhttp3:okhttp:${okHttpVersion}")

    // Paging 3
    implementation("androidx.paging:paging-runtime-ktx:${paging3Version}")
    implementation "androidx.room:room-paging:2.5.0"
    // Shimmer Effect
    implementation("com.facebook.shimmer:shimmer:0.5.0")

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
